CREATE TABLE dsc_changelog
(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	sha256 TEXT NOT NULL,
	epoch INTEGER NOT NULL,
	applied_at_epoch INTEGER,
	author_name TEXT NOT NULL,
	author_email TEXT NOT NULL
);

CREATE TABLE dsc_change_files
(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	changelog_id INTEGER NOT NULL REFERENCES dsc_changelog(id) ON DELETE CASCADE,
	file TEXT NOT NULL
);

CREATE TABLE dsc_config
(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	type TEXT NOT NULL,
	alias TEXT NOT NULL,
	dump_exec TEXT
);